import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/Components/share/Navbar";
import Footer from "@/Components/share/Footer";

export const metadata: Metadata = {
  title: "Fix It Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="fixed top-0 w-full z-50">
          <Navbar />
        </header>
        <main className="mt-20 container mx-auto sm:px-10">
          <section>{children}</section>
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
